sudo: required
services:
  - docker

before_install:
  - docker build -t continuestudying/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run continuestudying/react-test npm test -- --coverage

after_success:
  - docker build -t continuestudying/multi-client ./client
  - docker build -t continuestudying/multi-nginx ./nginx
  - docker build -t continuestudying/multi-server ./server
  - docker build -t continuestudying/multi-worker ./worker

  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Take those images and push them to the docker hub
  - docker push continuestudying/multi-client
  - docker push continuestudying/multi-nginx
  - docker push continuestudying/multi-server
  - docker push continuestudying/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-572689041991
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY